import Navbar from '@/components/NavBar';
import '../styles/globals.css';
import Footer from '@/components/Footer';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        {/* <Footer>Click me!</Footer> */}
      </body>
    </html>
  )
}
