import Navbar from '@/components/NavBar';
import '../styles/globals.css';
import Footer from '@/components/Footer';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

/**
 * Display the navigation bar at the top and then all other page content underneath.
 * @param children components
 * @returns React Component
 */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='flex flex-col h-screen'>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
